<?php
// $Id$

/**
 * @file
 *   This module is an example of a way to use the Appbar system to generate
 *   alerts when certain events occur.
 */

/**
 * Implementation of hook_user().
 */
function appbar_defaults_user($op, &$edit, &$account, $category = NULL) {
  global $user;
  if ($op == 'delete') {
    //If the administrator deleted the user, there will be a system message saying so, so we don't need an appbar alert.
    if ($user->uid != 1) {
      appbar_set_message(t('User %deleted was deleted by %deleter', array('%deleted' => theme('username', $account), '%deleter' => theme('username', $user))), 'user-delete-1', 1);
    }
  }
  elseif ($op == 'insert') {
    appbar_set_message(t('User %user has registered on @site.', array('%user' => theme('username', $account), '@site' => variable_get('site_name', 'Drupal'))), 'user-insert-1', 1);
    appbar_set_message(t('Welcome to @site, @user!', array('@site' => variable_get('site_name', 'Drupal'), '@user' => $account->name)), 'user-insert', $account->uid);
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function appbar_defaults_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  global $user;
  //Don't show a message to the user who performed the action because the system
  //provides its own message.
  if ($node->uid == $user->uid) {
    return;
  }
  if ($op == 'delete') {
    appbar_set_message(t('!user deleted your post %node.', array('%node' => $node->title, '!user' => theme('username', user_load(array('uid' => $user->uid))))), 'node-delete', $node->uid);
    appbar_set_message(t('!user deleted the node %node.', array('%node' => $node->title, '!user' => theme('username', user_load(array('uid' => $user->uid))))), 'node-delete-1', 1);
  }
  elseif ($op == 'insert') {
    appbar_set_message(t('!user added the node !node.', array('!node' => l($node->title, 'node/'. $node->nid), '!user' => theme('username', user_load(array('uid' => $user->uid))))), 'node-insert-1', 1);
  }
  elseif ($op == 'update') {
    appbar_set_message(t('!user updated your post !node.', array('!node' => l($node->title, 'node/'. $node->nid), '!user' => theme('username', user_load(array('uid' => $user->uid))))), 'node-update', $node->uid);
    appbar_set_message(t('!user updated the node !node.', array('!node' => l($node->title, 'node/'. $node->nid), '!user' => theme('username', user_load(array('uid' => $user->uid))))), 'node-update-1', 1);
  }
}

/**
 * Implementation of hook_comment().
 */
function appbar_defaults_comment(&$comment, $op) {
  global $user;
  //Don't show a message to the user who performed the action because the system
  //provides its own message.
  if ($comment->uid == $user->uid) {
    return;
  }
  if ($op == 'delete') {
    appbar_set_message(t('!user deleted your comment %comment.', array('%comment' => $comment->subject, '!user' => theme('username', user_load(array('uid' => $user->uid))))), 'comment-delete', $comment->uid);
    appbar_set_message(t('!user deleted the comment %comment.', array('%comment' => $comment->subject, '!user' => theme('username', user_load(array('uid' => $user->uid))))), 'comment-delete-1', 1);
  }
  elseif ($op == 'insert') {
    appbar_set_message(t('!user added the comment !comment.', array('!comment' => l($comment->subject, 'node/'. $comment->nid, array('fragment' => 'comment-'. $comment->cid)), '!user' => theme('username', user_load(array('uid' => $user->uid))))), 'comment-insert-1', 1);
  }
  elseif ($op == 'update') {
    appbar_set_message(t('!user updated your comment !comment.', array('!comment' => l($comment->subject, 'node/'. $comment->nid, array('fragment' => 'comment-'. $comment->cid)), '!user' => theme('username', user_load(array('uid' => $user->uid))))), 'comment-update', $comment->uid);
    appbar_set_message(t('!user updated the comment !comment.', array('!comment' => l($comment->subject, 'node/'. $comment->nid, array('fragment' => 'comment-'. $comment->cid)), '!user' => theme('username', user_load(array('uid' => $user->uid))))), 'comment-update-1', 1);
  }
}

/**
 * Implementation of hook_appbar_id().
 */
function appbar_defaults_appbar_id() {
  //It doesn't make sense to include 'status' in this array because we have an explicit setting for it.
  $a = array(
    'node-delete' => t('Node deletion (alerts author)'),
    'node-delete-1' => t('Node deletion (alerts User 1)'),
    'node-insert-1' => t('Node insertion (alerts User 1)'),
    'node-update' => t('Node updating (alerts author)'),
    'node-update-1' => t('Node updating (alerts User 1)'),
    'user-delete-1' => t('User deletion (alerts User 1)'),
    'user-insert' => t('User insertion (welcomes new user)'),
    'user-insert-1' => t('User insertion (alerts User 1)'),
  );
  if (module_exists('comment')) {
    $b = array(
      'comment-delete' => t('Comment deletion (alerts author)'),
      'comment-delete-1' => t('Comment deletion (alerts User 1)'),
      'comment-insert-1' => t('Comment insertion (alerts User 1)'),
      'comment-update' => t('Comment updating (alerts author)'),
      'comment-update-1' => t('Comment updating (alerts User 1)'),
    );
    $a = array_merge($b, $a);
  }
  return $a;
}